language: objective-c
before_install:
  - brew update
  - brew uninstall xctool
  - brew install xctool
  - export LANG=en_US.UTF-8
  - gem i cocoapods --no-ri --no-rdoc
xcode_workspace: ARTiledImageView.xcworkspace
xcode_scheme: Demo
xcode_sdk: iphonesimulator

